/*
 * WhatsApp Business API
 * See https://developers.facebook.com/docs/whatsapp
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * type of the message
 */
@JsonAdapter(MessageType.Adapter.class)public enum MessageType {
  
  AUDIO("audio"),
  
  CONTACTS("contacts"),
  
  DOCUMENT("document"),
  
  HSM("hsm"),
  
  IMAGE("image"),
  
  LOCATION("location"),
  
  TEXT("text"),
  
  VIDEO("video"),
  
  VOICE("voice"),
  
  UNKNOWN("unknown");

  private String value;

  MessageType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MessageType fromValue(String value) {
    for (MessageType b : MessageType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MessageType> {
    @Override
    public void write(final JsonWriter jsonWriter, final MessageType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MessageType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MessageType.fromValue(value);
    }
  }
}

