/*
 * WhatsApp Business API
 * See https://developers.facebook.com/docs/whatsapp
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Webhooks
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Webhooks {
  /**
   * Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.
   */
  @JsonAdapter(MaxConcurrentRequestsEnum.Adapter.class)
 public enum MaxConcurrentRequestsEnum {
    NUMBER_6(6),
    
    NUMBER_12(12),
    
    NUMBER_18(18),
    
    NUMBER_24(24);

    private Integer value;

    MaxConcurrentRequestsEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MaxConcurrentRequestsEnum fromValue(Integer value) {
      for (MaxConcurrentRequestsEnum b : MaxConcurrentRequestsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MaxConcurrentRequestsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MaxConcurrentRequestsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MaxConcurrentRequestsEnum read(final JsonReader jsonReader) throws IOException {
        Integer value =  jsonReader.nextInt();
        return MaxConcurrentRequestsEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MAX_CONCURRENT_REQUESTS = "max_concurrent_requests";
  @SerializedName(SERIALIZED_NAME_MAX_CONCURRENT_REQUESTS)
  private MaxConcurrentRequestsEnum maxConcurrentRequests = MaxConcurrentRequestsEnum.NUMBER_6;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public Webhooks() {
  }

  public Webhooks maxConcurrentRequests(MaxConcurrentRequestsEnum maxConcurrentRequests) {
    
    
    
    
    this.maxConcurrentRequests = maxConcurrentRequests;
    return this;
  }

   /**
   * Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.
   * @return maxConcurrentRequests
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "_6", value = "Configures the maximum number of inflight callback requests that are sent out. Can be set to 6 (default), 12, 18, or 24.")

  public MaxConcurrentRequestsEnum getMaxConcurrentRequests() {
    return maxConcurrentRequests;
  }


  public void setMaxConcurrentRequests(MaxConcurrentRequestsEnum maxConcurrentRequests) {
    
    
    
    this.maxConcurrentRequests = maxConcurrentRequests;
  }


  public Webhooks url(String url) {
    
    
    
    
    this.url = url;
    return this;
  }

   /**
   * Inbound and outbound notifications are routed to this URL. A HTTPS-based endpoint is required; HTTP will not work.
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<Webhook URL, https>", value = "Inbound and outbound notifications are routed to this URL. A HTTPS-based endpoint is required; HTTP will not work.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    
    
    
    this.url = url;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Webhooks instance itself
   */
  public Webhooks putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Webhooks webhooks = (Webhooks) o;
    return Objects.equals(this.maxConcurrentRequests, webhooks.maxConcurrentRequests) &&
        Objects.equals(this.url, webhooks.url)&&
        Objects.equals(this.additionalProperties, webhooks.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxConcurrentRequests, url, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Webhooks {\n");
    sb.append("    maxConcurrentRequests: ").append(toIndentedString(maxConcurrentRequests)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("max_concurrent_requests");
    openapiFields.add("url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Webhooks
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Webhooks.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Webhooks is not found in the empty JSON string", Webhooks.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Webhooks.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Webhooks' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Webhooks> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Webhooks.class));

       return (TypeAdapter<T>) new TypeAdapter<Webhooks>() {
           @Override
           public void write(JsonWriter out, Webhooks value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Webhooks read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Webhooks instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Webhooks given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Webhooks
  * @throws IOException if the JSON string is invalid with respect to Webhooks
  */
  public static Webhooks fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Webhooks.class);
  }

 /**
  * Convert an instance of Webhooks to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

