/*
 * WhatsApp Business API
 * See https://developers.facebook.com/docs/whatsapp
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HealthApi
 */
@Disabled
public class HealthApiTest {

    private static HealthApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new HealthApi(apiClient);
    }

    /**
     * Check-Health
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatusTest() throws ApiException {
        api.checkStatus()
                .execute();
        // TODO: test validations
    }

    /**
     * Get-App-Stats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAppStatsTest() throws ApiException {
        String format = null;
        Object response = api.getAppStats()
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get-DB-Stats
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDbStatsTest() throws ApiException {
        String format = null;
        Object response = api.getDbStats()
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get-Metrics (since v2.21.3)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getMetricsDataTest() throws ApiException {
        String format = null;
        Object response = api.getMetricsData()
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Get-Support-Info
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSupportInfoTest() throws ApiException {
        Object response = api.getSupportInfo()
                .execute();
        // TODO: test validations
    }

}
