/*
 * WhatsApp Business API
 * See https://developers.facebook.com/docs/whatsapp
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.io.File;
import com.konfigthis.client.model.GetProfileAboutResponse;
import com.konfigthis.client.model.GetProfilePhotoResponse;
import com.konfigthis.client.model.ProfileAbout;
import com.konfigthis.client.model.ProfileUpdatePhotoRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileApi
 */
@Disabled
public class ProfileApiTest {

    private static ProfileApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ProfileApi(apiClient);
    }

    /**
     * Get-Profile-About
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAboutTest() throws ApiException {
        GetProfileAboutResponse response = api.getAbout()
                .execute();
        // TODO: test validations
    }

    /**
     * Get-Profile-Photo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPhotoTest() throws ApiException {
        String format = null;
        GetProfilePhotoResponse response = api.getPhoto()
                .format(format)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete-Profile-Photo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removePhotoTest() throws ApiException {
        api.removePhoto()
                .execute();
        // TODO: test validations
    }

    /**
     * Update-Profile-About
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAboutTest() throws ApiException {
        String text = null;
        api.updateAbout(text)
                .execute();
        // TODO: test validations
    }

    /**
     * Update-Profile-Photo
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updatePhotoTest() throws ApiException {
        File _file = null;
        api.updatePhoto(_file)
                .execute();
        // TODO: test validations
    }

}
